/**
 * Where each projectile body sits in `public/art/bolt.webp`.
 *
 * Generated by `npm run bolt` — edit the body table in the packer, not this
 * file. One kind per row, frames across, left to right.
 *
 * The art is greyscale on purpose: a projectile takes its colour from the
 * ability that threw it, and a sprite with a colour baked in would throw that
 * away. It is tinted at draw time instead.
 *
 * CC0 pixel art spells by DevWizard — no attribution required, no share-alike,
 * which is why there is no credits file to go with it.
 */

import type { ProjectileKind } from '../sim/types'

export const BOLT_CELL = 32
export const BOLT_FRAMES = 6
export const BOLT_SRC = 'art/bolt.webp'

export const BOLT_ROW: Record<ProjectileKind, number> = {
  bolt: 0,
  dot: 1,
  heavy: 2,
  heal: 3,
}
