/**
 * Where each hit effect sits in `public/art/fx.webp`.
 *
 * Generated by `npm run fx` — edit the effect table in the packer, not this
 * file. One effect per row, frames across, left to right.
 *
 * The art is from the Superpowers asset packs and is CC0: no attribution
 * required, no share-alike. It is the lightest licence anything here runs
 * under, which is why there is no credits file to go with it.
 */

export const FX_CELL = 64
export const FX_SRC = 'art/fx.webp'

export const FX: Record<string, { row: number; frames: number }> = {
  burst: { row: 0, frames: 6 },
  flame: { row: 1, frames: 4 },
  holy: { row: 2, frames: 3 },
  bolt: { row: 3, frames: 6 },
  slash: { row: 4, frames: 5 },
  heal: { row: 5, frames: 7 },
  blast: { row: 6, frames: 3 },
  gust: { row: 7, frames: 5 },
}
