/**
 * Which block of `public/art/lpc.webp` belongs to each spec.
 *
 * Generated by `npm run lpc` — edit the layer table in the packer, not this
 * file.
 *
 * One run of cells a block, a subject owning `LPC_ANIMATIONS` of them. Along a
 * run are the four directions in LPC's own order — up, left, down, right — and
 * inside each direction `LPC_FRAMES` frames.
 *
 * Where a block sits and how big its cells are is `LPC_CELLS`, indexed by
 * `LPC_ROW[id] * LPC_ANIMATIONS + block` and holding `[x, y, w, h, foot]`.
 * A cell is wider and taller than the body it holds, because a longsword
 * mid-swing is, and blocks are sized one at a time because most of them are
 * not holding a longsword. So a cell is at
 *
 *   x + (direction * LPC_FRAMES + frame) * w,  y
 *
 * `LPC_BODY` is the square the body itself stands in, centred across the cell
 * whatever its width, and `foot` is how far down the cell its ground line sits
 * — draw the whole cell scaled so that `LPC_BODY` comes out the size the body
 * should be, with `foot` on the actor's own position.
 *
 * The art is Liberated Pixel Cup, variously CC-BY-SA 3.0, GPL 3.0, OGA-BY and
 * CC0. Attribution is a condition of those, and the list is in
 * `art/LPC-CREDITS.md`.
 */

/** The square a body stands in, centred across whatever cell holds it. */
export const LPC_BODY = 64
export const LPC_FRAMES = 5
export const LPC_DIRECTIONS = 4

/** Blocks per subject, in this order. A block is four directions. */
export const LPC_WALK = 0
export const LPC_ACTION = 1
export const LPC_ANIMATIONS = 2
export const LPC_SRC = 'art/lpc.webp'

/** Column order across a block, which is LPC's own direction order. */
export const LPC_UP = 0
export const LPC_LEFT = 1
export const LPC_DOWN = 2
export const LPC_RIGHT = 3

export const LPC_ROW: Record<string, number> = {
  'warrior-protection': 0,
  'warrior-arms': 1,
  'paladin-protection': 2,
  'paladin-holy': 3,
  'paladin-retribution': 4,
  'priest-discipline': 5,
  'priest-shadow': 6,
  'druid-guardian': 7,
  'druid-restoration': 8,
  'druid-balance': 9,
  'druid-feral': 10,
  'shaman-restoration': 11,
  'shaman-elemental': 12,
  'mage-frost': 13,
  'warlock-destruction': 14,
  'hunter-marksmanship': 15,
  'rogue-assassination': 16,
  'boss-whisper': 17,
  'boss-marrow': 18,
  'boss-host': 19,
  'boss-gift': 20,
  'boss-crowns': 21,
  'boss-crowns-2': 22,
  'boss-crowns-3': 23,
  'boss-flasks': 24,
  'boss-flasks-2': 25,
  'boss-confluence': 26,
  'boss-cold': 27,
  'boss-gorged': 28,
  'add-thrall': 29,
  'add-ooze': 30,
  'add-herald': 31,
  'add-bone': 32,
  'add-cult': 33,
  'add-ghoul': 34,
  'add-hulk': 35,
  'add-blood': 36,
  'add-vrykul': 37,
  'add-stone': 38,
  'add-crawler': 39,
  'add-drake': 40,
  'shield/crusader:slash:behind': 41,
  'shield/crusader:slash:front': 42,
  'shield/crusader:spellcast:behind': 43,
  'shield/crusader:spellcast:front': 44,
  'shield/heater:slash:behind': 45,
  'shield/heater:slash:front': 46,
  'shield/heater:spellcast:behind': 47,
  'shield/heater:spellcast:front': 48,
  'shield/plus:slash:behind': 49,
  'shield/plus:slash:front': 50,
  'shield/plus:spellcast:behind': 51,
  'shield/plus:spellcast:front': 52,
  'shield/scutum:slash:behind': 53,
  'shield/scutum:slash:front': 54,
  'shield/scutum:spellcast:behind': 55,
  'shield/scutum:spellcast:front': 56,
  'shield/spartan:slash:behind': 57,
  'shield/spartan:slash:front': 58,
  'shield/spartan:spellcast:behind': 59,
  'shield/spartan:spellcast:front': 60,
  'shield/two_engrailed:slash:behind': 61,
  'shield/two_engrailed:slash:front': 62,
  'shield/two_engrailed:spellcast:behind': 63,
  'shield/two_engrailed:spellcast:front': 64,
  'weapon/blunt/flail:slash:behind': 65,
  'weapon/blunt/flail:slash:front': 66,
  'weapon/blunt/flail:spellcast:behind': 67,
  'weapon/blunt/flail:spellcast:front': 68,
  'weapon/blunt/mace:slash:behind': 69,
  'weapon/blunt/mace:slash:front': 70,
  'weapon/blunt/mace:spellcast:behind': 71,
  'weapon/blunt/mace:spellcast:front': 72,
  'weapon/blunt/waraxe:slash:behind': 73,
  'weapon/blunt/waraxe:slash:front': 74,
  'weapon/magic/simple:spellcast:behind': 75,
  'weapon/magic/simple:spellcast:front': 76,
  'weapon/polearm/halberd:slash:behind': 77,
  'weapon/polearm/halberd:slash:front': 78,
  'weapon/polearm/scythe:slash:behind': 79,
  'weapon/polearm/scythe:slash:front': 80,
  'weapon/ranged/bow/great:shoot:behind': 81,
  'weapon/ranged/bow/great:shoot:front': 82,
  'weapon/ranged/bow/normal:shoot:behind': 83,
  'weapon/ranged/bow/normal:shoot:front': 84,
  'weapon/ranged/bow/recurve:shoot:behind': 85,
  'weapon/ranged/bow/recurve:shoot:front': 86,
  'weapon/sword/arming:slash:behind': 87,
  'weapon/sword/arming:slash:front': 88,
  'weapon/sword/arming:spellcast:behind': 89,
  'weapon/sword/arming:spellcast:front': 90,
  'weapon/sword/dagger:slash:behind': 91,
  'weapon/sword/dagger:slash:front': 92,
  'weapon/sword/longsword:slash:behind': 93,
  'weapon/sword/longsword:slash:front': 94,
  'weapon/sword/rapier:slash:behind': 95,
  'weapon/sword/rapier:slash:front': 96,
  'weapon/sword/rapier:spellcast:behind': 97,
  'weapon/sword/rapier:spellcast:front': 98,
  'weapon/sword/saber:slash:behind': 99,
  'weapon/sword/saber:slash:front': 100,
  'weapon/sword/saber:spellcast:behind': 101,
  'weapon/sword/saber:spellcast:front': 102,
  'weapon/sword/dagger:off:behind': 103,
  'weapon/sword/dagger:off:front': 104,
  'weapon/sword/rapier:off:behind': 105,
  'weapon/sword/rapier:off:front': 106,
  'weapon/sword/saber:off:behind': 107,
  'weapon/sword/saber:off:front': 108,
}

/**
 * Which weapons a spec might be carrying, as the two rows each one occupies —
 * the half that hangs behind the body and the half in front of it.
 *
 * A list rather than one, so a raid of eight warriors is eight swords. Which
 * of them a given body draws is the renderer's to decide and it decides off
 * the body's own id, which is stable for a fight and differs between
 * neighbours. A spec with no entry carries nothing: a bear has no hands.
 */
export const LPC_ARMS: Record<string, [number, number][]> = {
  // sword/arming, sword/saber, sword/rapier, blunt/mace, blunt/flail
  'warrior-protection': [[87, 88], [99, 100], [95, 96], [69, 70], [65, 66]],
  // sword/longsword, blunt/waraxe, polearm/halberd, polearm/scythe
  'warrior-arms': [[93, 94], [73, 74], [77, 78], [79, 80]],
  // sword/arming, sword/saber, sword/rapier, blunt/mace, blunt/flail
  'paladin-protection': [[87, 88], [99, 100], [95, 96], [69, 70], [65, 66]],
  // sword/longsword, blunt/waraxe, polearm/halberd, polearm/scythe
  'paladin-retribution': [[93, 94], [73, 74], [77, 78], [79, 80]],
  // sword/arming, sword/saber, sword/rapier, blunt/mace, blunt/flail
  'paladin-holy': [[89, 90], [101, 102], [97, 98], [71, 72], [67, 68]],
  // magic/simple
  'priest-discipline': [[75, 76]],
  // magic/simple
  'priest-shadow': [[75, 76]],
  // magic/simple
  'druid-restoration': [[75, 76]],
  // magic/simple
  'druid-balance': [[75, 76]],
  // magic/simple
  'shaman-restoration': [[75, 76]],
  // magic/simple
  'shaman-elemental': [[75, 76]],
  // magic/simple
  'mage-frost': [[75, 76]],
  // magic/simple
  'warlock-destruction': [[75, 76]],
  // ranged/bow/normal, ranged/bow/recurve, ranged/bow/great
  'hunter-marksmanship': [[83, 84], [85, 86], [81, 82]],
  // sword/dagger, sword/rapier, sword/saber
  'rogue-assassination': [[91, 92], [95, 96], [99, 100]],
  // blunt/waraxe
  'boss-marrow': [[73, 74]],
  // magic/simple
  'boss-whisper': [[75, 76]],
  // polearm/halberd
  'boss-gorged': [[77, 78]],
  // magic/simple
  'boss-crowns': [[75, 76]],
  // sword/rapier
  'boss-crowns-3': [[95, 96]],
}

/**
 * And what is on the other arm, the same way.
 *
 * A separate table because a shield is not a weapon: it is worn by whoever has
 * an arm spare rather than by whoever fights a particular way, and the two
 * lists have nothing to say to each other. The shields carry no class colour —
 * see the packer — so one row of them serves every class that picks it up.
 */
export const LPC_GUARD: Record<string, [number, number][]> = {
  // heater, crusader, scutum, spartan, plus, two_engrailed
  'warrior-protection': [[45, 46], [41, 42], [53, 54], [57, 58], [49, 50], [61, 62]],
  // heater, crusader, scutum, spartan, plus, two_engrailed
  'paladin-protection': [[45, 46], [41, 42], [53, 54], [57, 58], [49, 50], [61, 62]],
  // heater, crusader, scutum, spartan, plus, two_engrailed
  'paladin-holy': [[47, 48], [43, 44], [55, 56], [59, 60], [51, 52], [63, 64]],
}

/**
 * The second of a pair, in the same order as `LPC_ARMS` so that one number
 * picks both.
 *
 * Empty on the action block, on purpose: a body in this set swings one arm,
 * and the blade in the other one is put away for the four tenths of a second
 * that takes rather than left hanging off an arm that did not move.
 */
export const LPC_OFF: Record<string, [number, number][]> = {
  'rogue-assassination': [[103, 104], [105, 106], [107, 108]],
}

/** Every block's place and size in the sheet, as [x, y, w, h, foot]. */
export const LPC_CELLS: [number, number, number, number, number][] = [
  [1920, 889, 30, 64, 64],
  [0, 956, 52, 64, 64],
  [1040, 956, 30, 64, 64],
  [1640, 956, 52, 64, 64],
  [0, 1020, 30, 64, 64],
  [600, 1020, 52, 64, 64],
  [1640, 1020, 30, 64, 64],
  [2240, 1020, 48, 64, 64],
  [0, 1084, 30, 64, 64],
  [600, 1084, 52, 64, 64],
  [1640, 1084, 30, 64, 64],
  [2240, 1084, 48, 64, 64],
  [0, 1148, 30, 64, 64],
  [600, 1148, 48, 64, 64],
  [1560, 1148, 32, 64, 64],
  [2200, 1148, 52, 64, 64],
  [0, 1212, 30, 64, 64],
  [600, 1212, 48, 64, 64],
  [1560, 1212, 30, 64, 64],
  [2160, 1212, 48, 64, 64],
  [0, 1276, 44, 64, 64],
  [880, 1276, 52, 64, 64],
  [1920, 1276, 34, 64, 64],
  [0, 1340, 48, 64, 64],
  [960, 1340, 34, 64, 64],
  [1640, 1340, 48, 64, 64],
  [2600, 1340, 30, 64, 64],
  [0, 1404, 48, 64, 64],
  [960, 1404, 30, 64, 64],
  [1560, 1404, 48, 64, 64],
  [0, 1468, 44, 64, 64],
  [880, 1468, 46, 64, 64],
  [1800, 1468, 30, 64, 64],
  [0, 1532, 52, 64, 64],
  [1040, 1532, 28, 64, 64],
  [1600, 1532, 44, 64, 64],
  [2480, 1532, 30, 64, 64],
  [0, 1596, 52, 64, 64],
  [1040, 1596, 32, 64, 64],
  [1680, 1596, 52, 64, 64],
  [0, 1660, 28, 64, 64],
  [560, 1660, 52, 64, 64],
  [1600, 1660, 30, 64, 64],
  [2200, 1660, 48, 64, 64],
  [0, 1724, 32, 64, 64],
  [640, 1724, 52, 64, 64],
  [1680, 1724, 30, 64, 64],
  [0, 1788, 52, 64, 64],
  [1040, 1788, 30, 64, 64],
  [1640, 1788, 52, 64, 64],
  [0, 1852, 30, 64, 64],
  [600, 1852, 52, 64, 64],
  [1640, 1852, 30, 64, 64],
  [0, 1916, 52, 64, 64],
  [1040, 1916, 30, 64, 64],
  [1640, 1916, 52, 64, 64],
  [0, 1980, 32, 64, 64],
  [640, 1980, 52, 64, 64],
  [1680, 1980, 40, 64, 64],
  [0, 2044, 64, 64, 64],
  [1280, 2044, 30, 64, 64],
  [1880, 2044, 52, 64, 64],
  [0, 2108, 40, 64, 64],
  [800, 2108, 64, 64, 64],
  [2080, 2108, 56, 64, 64],
  [0, 755, 96, 67, 64],
  [0, 2172, 30, 64, 64],
  [600, 2172, 52, 64, 64],
  [1640, 2172, 30, 64, 64],
  [0, 2236, 52, 64, 64],
  [1040, 2236, 32, 64, 64],
  [1680, 2236, 52, 64, 64],
  [0, 2300, 62, 64, 64],
  [0, 85, 162, 82, 65],
  [1240, 2300, 42, 64, 64],
  [2080, 2300, 52, 64, 64],
  [0, 2364, 64, 64, 64],
  [1280, 2364, 64, 64, 64],
  [0, 2428, 40, 64, 64],
  [800, 2428, 52, 64, 64],
  [1840, 2428, 42, 64, 64],
  [0, 2492, 44, 64, 64],
  [880, 2492, 46, 64, 64],
  [1800, 2492, 46, 64, 64],
  [0, 2556, 44, 64, 64],
  [880, 2556, 44, 64, 64],
  [1760, 2556, 46, 64, 64],
  [0, 2620, 62, 64, 64],
  [1240, 2620, 44, 64, 64],
  [0, 2684, 58, 64, 64],
  [1160, 2684, 22, 64, 64],
  [1600, 2684, 2, 64, 64],
  [1640, 2684, 34, 64, 64],
  [2320, 2684, 34, 64, 64],
  [0, 2748, 22, 64, 64],
  [440, 2748, 30, 64, 64],
  [1040, 2748, 34, 64, 64],
  [1720, 2748, 50, 64, 64],
  [0, 2812, 46, 64, 64],
  [920, 2812, 46, 64, 64],
  [1840, 2812, 44, 64, 64],
  [0, 2876, 44, 64, 64],
  [880, 2876, 46, 64, 64],
  [1800, 2876, 62, 64, 64],
  [0, 2940, 44, 64, 64],
  [880, 2940, 60, 64, 64],
  [2080, 2940, 48, 64, 64],
  [0, 3004, 48, 64, 64],
  [960, 3004, 48, 64, 64],
  [1920, 3004, 48, 64, 64],
  [0, 3068, 48, 64, 64],
  [960, 3068, 64, 64, 64],
  [2240, 3068, 48, 64, 64],
  [0, 3132, 64, 64, 64],
  [1280, 3132, 46, 64, 64],
  [2200, 3132, 46, 64, 64],
  [0, 3196, 46, 64, 64],
  [920, 3196, 46, 64, 64],
  [1840, 3196, 46, 64, 64],
  [0, 3260, 62, 64, 64],
  [1240, 3260, 46, 64, 64],
  [0, 3324, 60, 64, 64],
  [1200, 3324, 46, 64, 64],
  [2120, 3324, 46, 64, 64],
  [0, 3388, 44, 64, 64],
  [880, 3388, 44, 64, 64],
  [1760, 3388, 46, 64, 64],
  [0, 3452, 62, 64, 64],
  [1240, 3452, 44, 64, 64],
  [0, 3516, 60, 64, 64],
  [1200, 3516, 40, 64, 64],
  [0, 3580, 108, 64, 64],
  [2160, 3580, 32, 64, 64],
  [0, 331, 102, 81, 64],
  [0, 3644, 40, 64, 64],
  [800, 3644, 2, 64, 64],
  [840, 3644, 32, 64, 64],
  [1480, 3644, 2, 64, 64],
  [1520, 3644, 52, 64, 64],
  [0, 3708, 66, 64, 64],
  [1320, 3708, 52, 64, 64],
  [0, 3772, 94, 64, 64],
  [1880, 3772, 52, 64, 64],
  [2920, 3772, 2, 64, 64],
  [0, 3836, 52, 64, 64],
  [1040, 3836, 2, 64, 64],
  [1080, 3836, 62, 64, 64],
  [0, 3900, 96, 64, 64],
  [1920, 3900, 30, 64, 64],
  [0, 412, 98, 71, 64],
  [0, 3964, 46, 64, 64],
  [920, 3964, 28, 64, 64],
  [1480, 3964, 26, 64, 64],
  [2000, 3964, 36, 64, 64],
  [0, 4028, 64, 64, 64],
  [0, 483, 126, 68, 68],
  [1280, 4028, 50, 64, 64],
  [0, 0, 120, 85, 64],
  [0, 4092, 60, 64, 64],
  [1200, 4092, 98, 64, 64],
  [0, 4156, 60, 64, 64],
  [0, 822, 104, 67, 64],
  [1200, 4156, 78, 64, 64],
  [2760, 4156, 2, 64, 64],
  [0, 4220, 38, 64, 64],
  [760, 4220, 64, 64, 64],
  [0, 4284, 74, 64, 64],
  [1480, 4284, 48, 64, 64],
  [2440, 4284, 28, 64, 64],
  [0, 4348, 50, 64, 64],
  [1000, 4348, 70, 64, 64],
  [2400, 4348, 2, 64, 64],
  [2440, 4348, 32, 64, 64],
  [0, 4412, 60, 64, 64],
  [1200, 4412, 26, 64, 64],
  [0, 4476, 98, 64, 64],
  [1960, 4476, 56, 64, 64],
  [0, 889, 96, 67, 64],
  [0, 4540, 26, 64, 64],
  [520, 4540, 2, 64, 64],
  [560, 4540, 56, 64, 64],
  [1680, 4540, 2, 64, 64],
  [1720, 4540, 24, 64, 64],
  [0, 4604, 62, 64, 64],
  [1240, 4604, 40, 64, 64],
  [0, 4668, 64, 64, 64],
  [1280, 4668, 64, 64, 64],
  [0, 551, 162, 68, 68],
  [0, 4732, 36, 64, 64],
  [0, 167, 126, 82, 65],
  [720, 4732, 48, 64, 64],
  [0, 619, 114, 68, 68],
  [1680, 4732, 62, 64, 64],
  [0, 249, 162, 82, 65],
  [0, 4796, 48, 64, 64],
  [960, 4796, 2, 64, 64],
  [1000, 4796, 62, 64, 64],
  [2240, 4796, 2, 64, 64],
  [2280, 4796, 28, 64, 64],
  [0, 4860, 96, 64, 64],
  [1920, 4860, 50, 64, 64],
  [0, 687, 98, 68, 64],
  [0, 4924, 28, 64, 64],
  [560, 4924, 2, 64, 64],
  [600, 4924, 50, 64, 64],
  [1600, 4924, 2, 64, 64],
  [1640, 4924, 40, 64, 64],
  [2440, 4924, 2, 64, 64],
  [2480, 4924, 24, 64, 64],
  [2960, 4924, 2, 64, 64],
  [0, 4988, 62, 64, 64],
  [1240, 4988, 2, 64, 64],
  [1280, 4988, 48, 64, 64],
  [2240, 4988, 2, 64, 64],
  [0, 5052, 50, 64, 64],
  [1000, 5052, 2, 64, 64],
  [1040, 5052, 28, 64, 64],
  [1600, 5052, 2, 64, 64],
]
