/**
 * Which block of `public/art/lpc.webp` belongs to each spec.
 *
 * Generated by `npm run lpc` — edit the layer table in the packer, not this
 * file.
 *
 * One run of cells a block, a subject owning `LPC_ANIMATIONS` of them. Along a
 * run are the four directions in LPC's own order — up, left, down, right — and
 * inside each direction `LPC_FRAMES` frames.
 *
 * Where a block sits and how big its cells are is `LPC_CELLS`, indexed by
 * `LPC_ROW[id] * LPC_ANIMATIONS + block` and holding `[x, y, w, h, foot]`.
 * A cell is wider and taller than the body it holds, because a longsword
 * mid-swing is, and blocks are sized one at a time because most of them are
 * not holding a longsword. So a cell is at
 *
 *   x + (direction * LPC_FRAMES + frame) * w,  y
 *
 * `LPC_BODY` is the square the body itself stands in, centred across the cell
 * whatever its width, and `foot` is how far down the cell its ground line sits
 * — draw the whole cell scaled so that `LPC_BODY` comes out the size the body
 * should be, with `foot` on the actor's own position.
 *
 * The art is Liberated Pixel Cup, variously CC-BY-SA 3.0, GPL 3.0, OGA-BY and
 * CC0. Attribution is a condition of those, and the list is in
 * `art/LPC-CREDITS.md`.
 */

/** The square a body stands in, centred across whatever cell holds it. */
export const LPC_BODY = 64
export const LPC_FRAMES = 5
export const LPC_DIRECTIONS = 4

/** Blocks per subject, in this order. A block is four directions. */
export const LPC_WALK = 0
export const LPC_ACTION = 1
export const LPC_ANIMATIONS = 2
export const LPC_SRC = 'art/lpc.webp'

/** Column order across a block, which is LPC's own direction order. */
export const LPC_UP = 0
export const LPC_LEFT = 1
export const LPC_DOWN = 2
export const LPC_RIGHT = 3

export const LPC_ROW: Record<string, number> = {
  'warrior-protection': 0,
  'warrior-arms': 1,
  'paladin-protection': 2,
  'paladin-holy': 3,
  'paladin-retribution': 4,
  'priest-discipline': 5,
  'priest-shadow': 6,
  'druid-guardian': 7,
  'druid-restoration': 8,
  'druid-balance': 9,
  'druid-feral': 10,
  'shaman-restoration': 11,
  'shaman-elemental': 12,
  'mage-frost': 13,
  'warlock-destruction': 14,
  'hunter-marksmanship': 15,
  'rogue-assassination': 16,
  'boss-warden': 17,
  'boss-choir': 18,
  'boss-tidebreaker': 19,
  'boss-watcher': 20,
  'boss-ledger': 21,
  'add-thrall': 22,
  'add-knell': 23,
  'add-herald': 24,
  'add-vessel': 25,
  'shield/crusader:slash:behind': 26,
  'shield/crusader:slash:front': 27,
  'shield/crusader:spellcast:behind': 28,
  'shield/crusader:spellcast:front': 29,
  'shield/heater:slash:behind': 30,
  'shield/heater:slash:front': 31,
  'shield/heater:spellcast:behind': 32,
  'shield/heater:spellcast:front': 33,
  'shield/plus:slash:behind': 34,
  'shield/plus:slash:front': 35,
  'shield/plus:spellcast:behind': 36,
  'shield/plus:spellcast:front': 37,
  'shield/scutum:slash:behind': 38,
  'shield/scutum:slash:front': 39,
  'shield/scutum:spellcast:behind': 40,
  'shield/scutum:spellcast:front': 41,
  'shield/spartan:slash:behind': 42,
  'shield/spartan:slash:front': 43,
  'shield/spartan:spellcast:behind': 44,
  'shield/spartan:spellcast:front': 45,
  'shield/two_engrailed:slash:behind': 46,
  'shield/two_engrailed:slash:front': 47,
  'shield/two_engrailed:spellcast:behind': 48,
  'shield/two_engrailed:spellcast:front': 49,
  'weapon/blunt/flail:slash:behind': 50,
  'weapon/blunt/flail:slash:front': 51,
  'weapon/blunt/flail:spellcast:behind': 52,
  'weapon/blunt/flail:spellcast:front': 53,
  'weapon/blunt/mace:slash:behind': 54,
  'weapon/blunt/mace:slash:front': 55,
  'weapon/blunt/mace:spellcast:behind': 56,
  'weapon/blunt/mace:spellcast:front': 57,
  'weapon/blunt/waraxe:slash:behind': 58,
  'weapon/blunt/waraxe:slash:front': 59,
  'weapon/magic/simple:spellcast:behind': 60,
  'weapon/magic/simple:spellcast:front': 61,
  'weapon/polearm/halberd:slash:behind': 62,
  'weapon/polearm/halberd:slash:front': 63,
  'weapon/polearm/scythe:slash:behind': 64,
  'weapon/polearm/scythe:slash:front': 65,
  'weapon/ranged/bow/great:shoot:behind': 66,
  'weapon/ranged/bow/great:shoot:front': 67,
  'weapon/ranged/bow/normal:shoot:behind': 68,
  'weapon/ranged/bow/normal:shoot:front': 69,
  'weapon/ranged/bow/recurve:shoot:behind': 70,
  'weapon/ranged/bow/recurve:shoot:front': 71,
  'weapon/sword/arming:slash:behind': 72,
  'weapon/sword/arming:slash:front': 73,
  'weapon/sword/arming:spellcast:behind': 74,
  'weapon/sword/arming:spellcast:front': 75,
  'weapon/sword/dagger:slash:behind': 76,
  'weapon/sword/dagger:slash:front': 77,
  'weapon/sword/longsword:slash:behind': 78,
  'weapon/sword/longsword:slash:front': 79,
  'weapon/sword/rapier:slash:behind': 80,
  'weapon/sword/rapier:slash:front': 81,
  'weapon/sword/rapier:spellcast:behind': 82,
  'weapon/sword/rapier:spellcast:front': 83,
  'weapon/sword/saber:slash:behind': 84,
  'weapon/sword/saber:slash:front': 85,
  'weapon/sword/saber:spellcast:behind': 86,
  'weapon/sword/saber:spellcast:front': 87,
  'weapon/sword/dagger:off:behind': 88,
  'weapon/sword/dagger:off:front': 89,
  'weapon/sword/rapier:off:behind': 90,
  'weapon/sword/rapier:off:front': 91,
  'weapon/sword/saber:off:behind': 92,
  'weapon/sword/saber:off:front': 93,
}

/**
 * Which weapons a spec might be carrying, as the two rows each one occupies —
 * the half that hangs behind the body and the half in front of it.
 *
 * A list rather than one, so a raid of eight warriors is eight swords. Which
 * of them a given body draws is the renderer's to decide and it decides off
 * the body's own id, which is stable for a fight and differs between
 * neighbours. A spec with no entry carries nothing: a bear has no hands.
 */
export const LPC_ARMS: Record<string, [number, number][]> = {
  // sword/arming, sword/saber, sword/rapier, blunt/mace, blunt/flail
  'warrior-protection': [[72, 73], [84, 85], [80, 81], [54, 55], [50, 51]],
  // sword/longsword, blunt/waraxe, polearm/halberd, polearm/scythe
  'warrior-arms': [[78, 79], [58, 59], [62, 63], [64, 65]],
  // sword/arming, sword/saber, sword/rapier, blunt/mace, blunt/flail
  'paladin-protection': [[72, 73], [84, 85], [80, 81], [54, 55], [50, 51]],
  // sword/longsword, blunt/waraxe, polearm/halberd, polearm/scythe
  'paladin-retribution': [[78, 79], [58, 59], [62, 63], [64, 65]],
  // sword/arming, sword/saber, sword/rapier, blunt/mace, blunt/flail
  'paladin-holy': [[74, 75], [86, 87], [82, 83], [56, 57], [52, 53]],
  // magic/simple
  'priest-discipline': [[60, 61]],
  // magic/simple
  'priest-shadow': [[60, 61]],
  // magic/simple
  'druid-restoration': [[60, 61]],
  // magic/simple
  'druid-balance': [[60, 61]],
  // magic/simple
  'shaman-restoration': [[60, 61]],
  // magic/simple
  'shaman-elemental': [[60, 61]],
  // magic/simple
  'mage-frost': [[60, 61]],
  // magic/simple
  'warlock-destruction': [[60, 61]],
  // ranged/bow/normal, ranged/bow/recurve, ranged/bow/great
  'hunter-marksmanship': [[68, 69], [70, 71], [66, 67]],
  // sword/dagger, sword/rapier, sword/saber
  'rogue-assassination': [[76, 77], [80, 81], [84, 85]],
}

/**
 * And what is on the other arm, the same way.
 *
 * A separate table because a shield is not a weapon: it is worn by whoever has
 * an arm spare rather than by whoever fights a particular way, and the two
 * lists have nothing to say to each other. The shields carry no class colour —
 * see the packer — so one row of them serves every class that picks it up.
 */
export const LPC_GUARD: Record<string, [number, number][]> = {
  // heater, crusader, scutum, spartan, plus, two_engrailed
  'warrior-protection': [[30, 31], [26, 27], [38, 39], [42, 43], [34, 35], [46, 47]],
  // heater, crusader, scutum, spartan, plus, two_engrailed
  'paladin-protection': [[30, 31], [26, 27], [38, 39], [42, 43], [34, 35], [46, 47]],
  // heater, crusader, scutum, spartan, plus, two_engrailed
  'paladin-holy': [[32, 33], [28, 29], [40, 41], [44, 45], [36, 37], [48, 49]],
}

/**
 * The second of a pair, in the same order as `LPC_ARMS` so that one number
 * picks both.
 *
 * Empty on the action block, on purpose: a body in this set swings one arm,
 * and the blade in the other one is put away for the four tenths of a second
 * that takes rather than left hanging off an arm that did not move.
 */
export const LPC_OFF: Record<string, [number, number][]> = {
  'rogue-assassination': [[88, 89], [90, 91], [92, 93]],
}

/** Every block's place and size in the sheet, as [x, y, w, h, foot]. */
export const LPC_CELLS: [number, number, number, number, number][] = [
  [1920, 740, 30, 64, 64],
  [0, 807, 52, 64, 64],
  [1040, 807, 30, 64, 64],
  [1640, 807, 52, 64, 64],
  [0, 871, 30, 64, 64],
  [600, 871, 52, 64, 64],
  [1640, 871, 30, 64, 64],
  [2240, 871, 48, 64, 64],
  [0, 935, 30, 64, 64],
  [600, 935, 52, 64, 64],
  [1640, 935, 30, 64, 64],
  [2240, 935, 48, 64, 64],
  [0, 999, 30, 64, 64],
  [600, 999, 48, 64, 64],
  [1560, 999, 32, 64, 64],
  [2200, 999, 52, 64, 64],
  [0, 1063, 30, 64, 64],
  [600, 1063, 48, 64, 64],
  [1560, 1063, 30, 64, 64],
  [2160, 1063, 48, 64, 64],
  [0, 1127, 44, 64, 64],
  [880, 1127, 52, 64, 64],
  [1920, 1127, 34, 64, 64],
  [0, 1191, 48, 64, 64],
  [960, 1191, 34, 64, 64],
  [1640, 1191, 48, 64, 64],
  [2600, 1191, 30, 64, 64],
  [0, 1255, 48, 64, 64],
  [960, 1255, 30, 64, 64],
  [1560, 1255, 48, 64, 64],
  [0, 1319, 44, 64, 64],
  [880, 1319, 46, 64, 64],
  [1800, 1319, 30, 64, 64],
  [0, 1383, 52, 64, 64],
  [1040, 1383, 30, 64, 64],
  [1640, 1383, 52, 64, 64],
  [0, 1447, 30, 64, 64],
  [600, 1447, 52, 64, 64],
  [1640, 1447, 30, 64, 64],
  [0, 1511, 52, 64, 64],
  [1040, 1511, 30, 64, 64],
  [1640, 1511, 52, 64, 64],
  [0, 1575, 30, 64, 64],
  [600, 1575, 52, 64, 64],
  [1640, 1575, 40, 64, 64],
  [0, 1639, 64, 64, 64],
  [1280, 1639, 30, 64, 64],
  [1880, 1639, 52, 64, 64],
  [0, 1703, 40, 64, 64],
  [800, 1703, 64, 64, 64],
  [2080, 1703, 30, 64, 64],
  [0, 1767, 52, 64, 64],
  [1040, 1767, 46, 64, 64],
  [1960, 1767, 46, 64, 64],
  [0, 1831, 44, 64, 64],
  [880, 1831, 44, 64, 64],
  [1760, 1831, 46, 64, 64],
  [0, 1895, 62, 64, 64],
  [1240, 1895, 44, 64, 64],
  [0, 1959, 58, 64, 64],
  [1160, 1959, 22, 64, 64],
  [1600, 1959, 2, 64, 64],
  [1640, 1959, 34, 64, 64],
  [2320, 1959, 34, 64, 64],
  [0, 2023, 22, 64, 64],
  [440, 2023, 30, 64, 64],
  [1040, 2023, 34, 64, 64],
  [1720, 2023, 50, 64, 64],
  [0, 2087, 46, 64, 64],
  [920, 2087, 46, 64, 64],
  [1840, 2087, 44, 64, 64],
  [0, 2151, 44, 64, 64],
  [880, 2151, 46, 64, 64],
  [1800, 2151, 62, 64, 64],
  [0, 2215, 44, 64, 64],
  [880, 2215, 60, 64, 64],
  [2080, 2215, 48, 64, 64],
  [0, 2279, 48, 64, 64],
  [960, 2279, 48, 64, 64],
  [1920, 2279, 48, 64, 64],
  [0, 2343, 48, 64, 64],
  [960, 2343, 64, 64, 64],
  [2240, 2343, 48, 64, 64],
  [0, 2407, 64, 64, 64],
  [1280, 2407, 46, 64, 64],
  [2200, 2407, 46, 64, 64],
  [0, 2471, 46, 64, 64],
  [920, 2471, 46, 64, 64],
  [1840, 2471, 46, 64, 64],
  [0, 2535, 62, 64, 64],
  [1240, 2535, 46, 64, 64],
  [0, 2599, 60, 64, 64],
  [1200, 2599, 46, 64, 64],
  [2120, 2599, 46, 64, 64],
  [0, 2663, 44, 64, 64],
  [880, 2663, 44, 64, 64],
  [1760, 2663, 46, 64, 64],
  [0, 2727, 62, 64, 64],
  [1240, 2727, 44, 64, 64],
  [0, 2791, 60, 64, 64],
  [1200, 2791, 40, 64, 64],
  [0, 2855, 108, 64, 64],
  [2160, 2855, 32, 64, 64],
  [0, 249, 102, 81, 64],
  [0, 2919, 40, 64, 64],
  [800, 2919, 2, 64, 64],
  [840, 2919, 32, 64, 64],
  [1480, 2919, 2, 64, 64],
  [1520, 2919, 52, 64, 64],
  [0, 2983, 66, 64, 64],
  [1320, 2983, 52, 64, 64],
  [0, 3047, 94, 64, 64],
  [1880, 3047, 52, 64, 64],
  [2920, 3047, 2, 64, 64],
  [0, 3111, 52, 64, 64],
  [1040, 3111, 2, 64, 64],
  [1080, 3111, 62, 64, 64],
  [0, 3175, 96, 64, 64],
  [1920, 3175, 30, 64, 64],
  [0, 330, 98, 71, 64],
  [0, 3239, 46, 64, 64],
  [920, 3239, 28, 64, 64],
  [1480, 3239, 26, 64, 64],
  [2000, 3239, 36, 64, 64],
  [0, 3303, 64, 64, 64],
  [0, 401, 126, 68, 68],
  [1280, 3303, 50, 64, 64],
  [0, 0, 120, 85, 64],
  [0, 3367, 60, 64, 64],
  [1200, 3367, 98, 64, 64],
  [0, 3431, 60, 64, 64],
  [0, 673, 104, 67, 64],
  [1200, 3431, 78, 64, 64],
  [2760, 3431, 2, 64, 64],
  [0, 3495, 38, 64, 64],
  [760, 3495, 64, 64, 64],
  [0, 3559, 74, 64, 64],
  [1480, 3559, 48, 64, 64],
  [2440, 3559, 28, 64, 64],
  [0, 3623, 50, 64, 64],
  [1000, 3623, 70, 64, 64],
  [2400, 3623, 2, 64, 64],
  [2440, 3623, 32, 64, 64],
  [0, 3687, 60, 64, 64],
  [1200, 3687, 26, 64, 64],
  [0, 3751, 98, 64, 64],
  [1960, 3751, 56, 64, 64],
  [0, 740, 96, 67, 64],
  [0, 3815, 26, 64, 64],
  [520, 3815, 2, 64, 64],
  [560, 3815, 56, 64, 64],
  [1680, 3815, 2, 64, 64],
  [1720, 3815, 24, 64, 64],
  [0, 3879, 62, 64, 64],
  [1240, 3879, 40, 64, 64],
  [0, 3943, 64, 64, 64],
  [1280, 3943, 64, 64, 64],
  [0, 469, 162, 68, 68],
  [0, 4007, 36, 64, 64],
  [0, 85, 126, 82, 65],
  [720, 4007, 48, 64, 64],
  [0, 537, 114, 68, 68],
  [1680, 4007, 62, 64, 64],
  [0, 167, 162, 82, 65],
  [0, 4071, 48, 64, 64],
  [960, 4071, 2, 64, 64],
  [1000, 4071, 62, 64, 64],
  [2240, 4071, 2, 64, 64],
  [2280, 4071, 28, 64, 64],
  [0, 4135, 96, 64, 64],
  [1920, 4135, 50, 64, 64],
  [0, 605, 98, 68, 64],
  [0, 4199, 28, 64, 64],
  [560, 4199, 2, 64, 64],
  [600, 4199, 50, 64, 64],
  [1600, 4199, 2, 64, 64],
  [1640, 4199, 40, 64, 64],
  [2440, 4199, 2, 64, 64],
  [2480, 4199, 24, 64, 64],
  [2960, 4199, 2, 64, 64],
  [0, 4263, 62, 64, 64],
  [1240, 4263, 2, 64, 64],
  [1280, 4263, 48, 64, 64],
  [2240, 4263, 2, 64, 64],
  [0, 4327, 50, 64, 64],
  [1000, 4327, 2, 64, 64],
  [1040, 4327, 28, 64, 64],
  [1600, 4327, 2, 64, 64],
]
