/**
 * Where each portrait sits in `public/art/portraits.webp`.
 *
 * Generated by `npm run portraits` — regenerate the art or edit the packer,
 * not this file. Keys are `<class>-<spec>` and `boss-<id>`, which is what the
 * roster and the encounter table already call them.
 */

export const PORTRAIT_CELL = 192
export const PORTRAIT_SRC = 'art/portraits.webp'

export const PORTRAITS: Record<string, readonly [number, number]> = {
  'boss-choir': [0, 0],
  'boss-ledger': [192, 0],
  'boss-tidebreaker': [384, 0],
  'boss-warden': [576, 0],
  'boss-watcher': [768, 0],
  'druid-balance': [960, 0],
  'druid-feral': [0, 192],
  'druid-guardian': [192, 192],
  'druid-restoration': [384, 192],
  'hunter-marksmanship': [576, 192],
  'mage-frost': [768, 192],
  'paladin-holy': [960, 192],
  'paladin-protection': [0, 384],
  'paladin-retribution': [192, 384],
  'priest-discipline': [384, 384],
  'priest-shadow': [576, 384],
  'rogue-assassination': [768, 384],
  'shaman-elemental': [960, 384],
  'shaman-restoration': [0, 576],
  'warlock-destruction': [192, 576],
  'warrior-arms': [384, 576],
  'warrior-protection': [576, 576],
}
