/**
 * Where each prop sits in `public/art/props.webp`, as [x, y, w, h].
 *
 * Generated by `npm run tiles` — edit the piece table in the packer, not this
 * file. Every piece names an author and the build refuses one that does not;
 * the credits are in `art/LPC-TERRAIN-CREDITS.md`.
 */

export const PROPS_SRC = 'art/props.webp'

export const PROPS: Record<string, [number, number, number, number]> = {
  'cross': [60, 0, 32, 64],
  'tomb': [0, 0, 60, 96],
  'grave-round': [156, 0, 32, 50],
  'grave-rip': [188, 0, 32, 50],
  'grave-pair': [92, 0, 64, 54],
  'cross-wood': [220, 0, 32, 46],
  'rock': [0, 96, 32, 32],
  'rocks': [32, 96, 32, 32],
}

export const PROP_IDS = Object.keys(PROPS)
