/**
 * Where each prop sits in `public/art/props.webp`, as [x, y, w, h].
 *
 * Generated by `npm run tiles` — edit the piece table in the packer, not this
 * file. Every piece names an author and the build refuses one that does not;
 * the credits are in `art/LPC-TERRAIN-CREDITS.md`.
 */

export const PROPS_SRC = 'art/props.webp'

export const PROPS: Record<string, [number, number, number, number]> = {
  'cross': [32, 96, 32, 44],
  'tomb': [0, 0, 60, 96],
  'grave-round': [188, 0, 32, 50],
  'grave-rip': [220, 0, 32, 50],
  'grave-pair': [124, 0, 64, 54],
  'cross-wood': [0, 96, 32, 46],
  'floor-slate': [64, 96, 32, 32],
  'floor-sand': [96, 96, 32, 32],
  'floor-earth': [128, 96, 32, 32],
  'floor-clay': [160, 96, 32, 32],
  'floor-cobble': [192, 96, 32, 32],
  'boulder': [224, 96, 32, 32],
  'menhir': [60, 0, 32, 64],
  'scatter': [0, 142, 32, 32],
  'rubble-a': [32, 142, 32, 32],
  'rubble-b': [64, 142, 32, 32],
  'pebbles': [92, 0, 32, 64],
}

export const PROP_IDS = Object.keys(PROPS)
