/**
 * Where each prop sits in `public/art/props.webp`, as [x, y, w, h].
 *
 * Generated by `npm run tiles` — edit the piece table in the packer, not this
 * file. Every piece names an author and the build refuses one that does not;
 * the credits are in `art/LPC-TERRAIN-CREDITS.md`.
 */

export const PROPS_SRC = 'art/props.webp'

export const PROPS: Record<string, [number, number, number, number]> = {
  'cross': [64, 114, 32, 44],
  'tomb': [36, 0, 60, 96],
  'grave-round': [224, 0, 32, 50],
  'grave-rip': [0, 114, 32, 50],
  'grave-pair': [160, 0, 64, 54],
  'cross-wood': [32, 114, 32, 46],
  'floor-slate': [96, 114, 32, 32],
  'floor-sand': [128, 114, 32, 32],
  'floor-earth': [160, 114, 32, 32],
  'floor-clay': [192, 114, 32, 32],
  'floor-cobble': [224, 114, 32, 32],
  'boulder': [0, 164, 32, 32],
  'menhir': [96, 0, 32, 64],
  'scatter': [32, 164, 32, 32],
  'rubble-a': [64, 164, 32, 32],
  'rubble-b': [96, 164, 32, 32],
  'pebbles': [128, 0, 32, 64],
  'brazier': [128, 164, 31, 30],
  'cauldron': [159, 164, 27, 30],
  'column': [0, 0, 36, 114],
}

export const PROP_IDS = Object.keys(PROPS)
