/**
 * Where each field sprite sits in `public/art/sprites.webp`.
 *
 * Generated by `npm run sprites` — regenerate the art or edit the packer, not
 * this file. Keys are `<class>-<spec>` and `boss-<id>`, which is what the
 * simulation already calls them.
 */

export const SPRITE_CELL = 160
export const SPRITE_SRC = 'art/sprites.webp'

export const SPRITES: Record<string, readonly [number, number]> = {
  'boss-choir': [0, 0],
  'boss-ledger': [160, 0],
  'boss-tidebreaker': [320, 0],
  'boss-warden': [480, 0],
  'boss-watcher': [640, 0],
  'druid-balance': [0, 160],
  'druid-feral': [160, 160],
  'druid-guardian': [320, 160],
  'druid-restoration': [480, 160],
  'hunter-marksmanship': [640, 160],
  'mage-frost': [0, 320],
  'paladin-holy': [160, 320],
  'paladin-protection': [320, 320],
  'paladin-retribution': [480, 320],
  'priest-discipline': [640, 320],
  'priest-shadow': [0, 480],
  'rogue-assassination': [160, 480],
  'shaman-elemental': [320, 480],
  'shaman-restoration': [480, 480],
  'warlock-destruction': [640, 480],
  'warrior-arms': [0, 640],
  'warrior-protection': [160, 640],
}
