/**
 * Eighty-two icons into one file, and a table saying where each one landed.
 *
 * Shipping them loose would put eighty-two entries in the service worker's
 * precache and eighty-two requests on a first paint — on the phone this game
 * is aimed at, that is the whole budget spent on decoration. One sheet is one
 * request and one cache entry.
 *
 * The browser does the packing. Node has no image encoder, and `visualcheck`
 * already brought a real one into this repo: a canvas can decode the frames,
 * draw them into a grid, and encode WebP, which for painted art is a fraction
 * of the PNG. That is worth caring about here — the whole build is 173 kB, so
 * an atlas is the largest thing the game would ever have loaded.
 *
 * Order is by id and the grid is fixed width, so adding an ability in the
 * middle of `abilities.ts` moves icons within the sheet but the table moves
 * with them, and the file is byte-stable when nothing changed.
 *
 *   npm run atlas
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { chromium } from 'playwright'

import { iconJobs } from './artprompt'

const SRC = resolve(process.cwd(), 'art/icons')
const IMAGE = resolve(process.cwd(), 'public/art/icons.webp')
const TABLE = resolve(process.cwd(), 'src/render/atlas.ts')

/**
 * An icon is drawn at roughly forty CSS pixels inside a round button. Ninety-
 * six covers that at a device pixel ratio of two with room to spare, and the
 * ratio is capped at two on the way in.
 */
const CELL = 96

/** Wide enough that the sheet stays close to square at eighty-odd icons. */
const COLS = 10

/**
 * Quality is a real decision, not a default: this is the only bitmap the game
 * loads, and painted art at 96px hides compression that would be obvious on a
 * photograph.
 */
const QUALITY = 0.82

async function main(): Promise<void> {
  const jobs = iconJobs()
  const have = jobs.filter((job) => existsSync(resolve(SRC, `${job.id}.jpg`)))
  const missing = jobs.length - have.length

  if (have.length === 0) {
    console.error(`no icons in art/icons — run \`npm run artgen -- --write\` first`)
    process.exit(1)
  }

  const rows = Math.ceil(have.length / COLS)
  const width = COLS * CELL
  const height = rows * CELL

  const cells = have.map((job, index) => ({
    id: job.id,
    x: (index % COLS) * CELL,
    y: Math.floor(index / COLS) * CELL,
    data: `data:image/jpeg;base64,${readFileSync(resolve(SRC, `${job.id}.jpg`)).toString('base64')}`,
  }))

  const browser = await chromium.launch()
  let encoded: string
  try {
    const page = await browser.newPage()
    await page.setContent('<!doctype html><meta charset="utf-8">', { waitUntil: 'load' })
    encoded = await page.evaluate(
      async ({ cells, width, height, cell, quality }) => {
        const canvas = document.createElement('canvas')
        canvas.width = width
        canvas.height = height
        const ctx = canvas.getContext('2d')!
        // Transparent ground, not the game's background: the button behind an
        // icon is not always the same colour, and baking one in would leave a
        // square of the wrong dark on every other surface.
        ctx.clearRect(0, 0, width, height)

        for (const c of cells) {
          const image = new Image()
          image.src = c.data
          await image.decode()
          ctx.drawImage(image, c.x, c.y, cell, cell)
        }
        return canvas.toDataURL('image/webp', quality)
      },
      { cells, width, height, cell: CELL, quality: QUALITY },
    )
  } finally {
    await browser.close()
  }

  mkdirSync(resolve(process.cwd(), 'public/art'), { recursive: true })
  const bytes = Buffer.from(encoded.slice(encoded.indexOf(',') + 1), 'base64')
  writeFileSync(IMAGE, bytes)

  const entries = cells.map((c) => `  ${c.id}: [${c.x}, ${c.y}],`).join('\n')
  writeFileSync(
    TABLE,
    `/**
 * Where each ability icon sits in \`public/art/icons.webp\`.
 *
 * Generated by \`npm run atlas\` — edit the art or the packer, not this file.
 */

export const ATLAS_CELL = ${CELL}
export const ATLAS_SRC = 'art/icons.webp'

export const ATLAS: Record<string, readonly [number, number]> = {
${entries}
}
`,
  )

  const kb = (bytes.length / 1024).toFixed(1)
  console.log(`atlas: ${have.length} icons, ${width}x${height}, ${kb} kB webp`)
  if (missing > 0) console.log(`  ${missing} abilities have no art yet`)
}

main()
