/**
 * The portraits into one sheet, at the size they are actually drawn.
 *
 * The generated files are 512 square because that is what the service returns,
 * and a class card is 120x65 CSS pixels. Shipping the originals would put two
 * thirds of a megabyte on the wire to fill a thumbnail — on a game whose whole
 * build is 173 kB, the art would be the game.
 *
 * So they are packed the way the icons are: one sheet, one request, one cache
 * entry, at a cell size chosen from the largest slot that draws them rather
 * than from what the generator happened to produce.
 *
 * Kept separate from `atlas.ts` even though both pack a sheet. That one takes
 * monochrome SVGs and recolours them by school; this takes photographs of a
 * kind and only resizes. Sharing the file would mean a flag deciding which
 * half runs.
 *
 *   npm run portraits
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { chromium } from 'playwright'

const SRC = resolve(process.cwd(), 'art/portraits')
const IMAGE = resolve(process.cwd(), 'public/art/portraits.webp')
const TABLE = resolve(process.cwd(), 'src/render/portraits.ts')

/**
 * The card is 120x65 CSS and the sheet is sampled at up to twice that, so 192
 * covers the card with room and still reads in the larger panel under the grid.
 * Going to 256 costs about half again in bytes for detail the card throws away.
 */
const CELL = 192

/** Six across keeps twenty-two cells close to square. */
const COLS = 6

/**
 * Lower than the icon sheet on purpose. Those are flat colour where any
 * artefact shows; these are painted, which is exactly what this hides.
 */
const QUALITY = 0.72

async function main(): Promise<void> {
  if (!existsSync(SRC)) {
    console.error('no art/portraits — run `npm run artgen -- --write` first')
    process.exit(1)
  }

  // Sorted, so the sheet is byte-stable and a regenerated portrait does not
  // reshuffle the table.
  const ids = readdirSync(SRC)
    .filter((f) => f.endsWith('.jpg'))
    .map((f) => f.slice(0, -4))
    .sort()

  if (ids.length === 0) {
    console.error('no portraits in art/portraits')
    process.exit(1)
  }

  const cells = ids.map((id, index) => ({
    id,
    x: (index % COLS) * CELL,
    y: Math.floor(index / COLS) * CELL,
    data: `data:image/jpeg;base64,${readFileSync(resolve(SRC, `${id}.jpg`)).toString('base64')}`,
  }))

  const width = COLS * CELL
  const height = Math.ceil(cells.length / COLS) * CELL

  const browser = await chromium.launch()
  let encoded: string
  try {
    const page = await browser.newPage()
    await page.setContent('<!doctype html><meta charset="utf-8">', { waitUntil: 'load' })
    encoded = await page.evaluate(
      async ({ cells, width, height, cell, quality }) => {
        const canvas = document.createElement('canvas')
        canvas.width = width
        canvas.height = height
        const ctx = canvas.getContext('2d')!
        ctx.imageSmoothingQuality = 'high'

        for (const c of cells) {
          const image = new Image()
          image.src = c.data
          await image.decode()
          ctx.drawImage(image, c.x, c.y, cell, cell)
        }
        return canvas.toDataURL('image/webp', quality)
      },
      { cells, width, height, cell: CELL, quality: QUALITY },
    )
  } finally {
    await browser.close()
  }

  mkdirSync(resolve(process.cwd(), 'public/art'), { recursive: true })
  const bytes = Buffer.from(encoded.slice(encoded.indexOf(',') + 1), 'base64')
  writeFileSync(IMAGE, bytes)

  const entries = cells.map((c) => `  '${c.id}': [${c.x}, ${c.y}],`).join('\n')
  writeFileSync(
    TABLE,
    `/**
 * Where each portrait sits in \`public/art/portraits.webp\`.
 *
 * Generated by \`npm run portraits\` — regenerate the art or edit the packer,
 * not this file. Keys are \`<class>-<spec>\` and \`boss-<id>\`, which is what the
 * roster and the encounter table already call them.
 */

export const PORTRAIT_CELL = ${CELL}
export const PORTRAIT_SRC = 'art/portraits.webp'

export const PORTRAITS: Record<string, readonly [number, number]> = {
${entries}
}
`,
  )

  const kb = (bytes.length / 1024).toFixed(1)
  const before = ids.reduce((n, id) => n + readFileSync(resolve(SRC, `${id}.jpg`)).length, 0)
  console.log(`portraits: ${ids.length} in ${width}x${height}, ${kb} kB webp`)
  console.log(`  source was ${(before / 1024).toFixed(0)} kB`)
}

main()
